### ISSUE TITLE
Gitの確認

### ISSUE THREAD

**Issue by n0bisuke** [n0bisuke/gs5th#2]
まずはこのリポジトリに 

https://github.com/n0bisuke/gs5th

それぞれ名前つけたフォルダを用意したので自分の名前のフォルダに自分の企画書をおいてみてください

(Gitをどれくらい使えるのかテストもかねてます笑

**Comment by n0bisuke** [comment]
そういえば

各自、GitHubのアカウントを書いて下さい。

**Comment by ghost** [comment]
https://github.com/gs05-26-TeruyoshiTakemoto
26番竹本です。

**Comment by n0bisuke** [comment]
@gs05-26-TeruyoshiTakemoto ありがとうございます。
権限追加しましたのでプッシュできると思います。

**Comment by n0bisuke** [comment]
https://github.com/n0bisuke/gs5th/invitations これってみれますかね？

**Comment by ghost** [comment]
acceptしました

**Comment by GS05-ID-yuta-nakamura** [comment]
https://github.com/GS05-ID-yuta-nakamura
35番中村です。よろしくお願いします。

**Comment by n0bisuke** [comment]
@GS05-ID-yuta-nakamura https://github.com/n0bisuke/gs5th/invitations 追加しました

**Comment by GS05-13-ShuntaroOizumi** [comment]
https://github.com/GS05-13-ShuntaroOizumi
13番大泉です。よろしくお願いします。

**Comment by n0bisuke** [comment]
@GS05-13-ShuntaroOizumi https://github.com/n0bisuke/gs5th/invitations 追加しましたよ〜

**Comment by daisuke-matsumoto** [comment]
https://github.com/GS05-44-MatsumotoDaisuke

すみません。出遅れました。44番松本です。

**Comment by n0bisuke** [comment]
GS05-44-MatsumotoDaisukeとGS05-09-ImaiYuriのアカウントに権限追加しました
https://github.com/n0bisuke/gs5th/invitations 

プッシュできるはずです。
